# DCEC 단계별 서비스 배포: 1단계(Postgres)
# /volume1/dev/docker/postgres-only-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dcec-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: data!5522
      TZ: Asia/Seoul
    volumes:
      - /volume1/dev/docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
