version: '3.8'

networks:
  uptime-network:
    driver: bridge

volumes:
  uptime_data:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "31003:3001"
    volumes:
      - uptime_data:/app/data
    networks:
      - uptime-network
    environment:
      UPTIME_KUMA_PORT: 3001
      UPTIME_KUMA_HOST: 0.0.0.0
