version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: dcec-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=dcec_n8n_2024
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://192.168.0.5:5678/
      - GENERIC_TIMEZONE=Asia/Seoul
      - DB_TYPE=sqlite
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
    volumes:
      - n8n_data:/home/node/.n8n
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dcec_network

volumes:
  n8n_data:
    driver: local
    name: dcec_n8n_data

networks:
  dcec_network:
    driver: bridge
    name: dcec_network
